// Code generated by "stringer -type=ResponseMessage"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginPasswordMismatch-0]
	_ = x[LoginUnverified-1]
	_ = x[RegisterEmailUsed-2]
	_ = x[EmailNotFound-3]
	_ = x[VerifyOtpExpired-4]
	_ = x[UserAlreadyVerified-5]
	_ = x[AccessNotAllowed-6]
	_ = x[SessionExpired-7]
	_ = x[LogoutSuccess-8]
	_ = x[LoginSuccess-9]
	_ = x[RegisterSuccess-10]
	_ = x[VerifyOtpSuccess-11]
	_ = x[ResendOtpSuccess-12]
	_ = x[UserNotFound-13]
	_ = x[CreateUser-14]
	_ = x[UpdateUser-15]
	_ = x[DeleteUser-16]
	_ = x[GetDetailUser-17]
	_ = x[GetListUser-18]
}

const _ResponseMessage_name = "LoginPasswordMismatchLoginUnverifiedRegisterEmailUsedEmailNotFoundVerifyOtpExpiredUserAlreadyVerifiedAccessNotAllowedSessionExpiredLogoutSuccessLoginSuccessRegisterSuccessVerifyOtpSuccessResendOtpSuccessUserNotFoundCreateUserUpdateUserDeleteUserGetDetailUserGetListUser"

var _ResponseMessage_index = [...]uint16{0, 21, 36, 53, 66, 82, 101, 117, 131, 144, 156, 171, 187, 203, 215, 225, 235, 245, 258, 269}

func (i ResponseMessage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResponseMessage_index)-1 {
		return "ResponseMessage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseMessage_name[_ResponseMessage_index[idx]:_ResponseMessage_index[idx+1]]
}
