// Code generated by "stringer -type=ChatEvent"; DO NOT EDIT.

package payload

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotifyJoin-0]
	_ = x[NotifyLeave-1]
	_ = x[NotifyOnline-2]
	_ = x[NotifyOffline-3]
	_ = x[Message-4]
	_ = x[AlertError-5]
}

const _ChatEvent_name = "NotifyJoinNotifyLeaveNotifyOnlineNotifyOfflineMessageAlertError"

var _ChatEvent_index = [...]uint8{0, 10, 21, 33, 46, 53, 63}

func (i ChatEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChatEvent_index)-1 {
		return "ChatEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChatEvent_name[_ChatEvent_index[idx]:_ChatEvent_index[idx+1]]
}
