// Code generated by "stringer -type=ChatEvent"; DO NOT EDIT.

package payload

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Notify_join-0]
	_ = x[Notify_leave-1]
	_ = x[Notify_online-2]
	_ = x[Notify_offline-3]
	_ = x[Message-4]
	_ = x[Alert_error-5]
}

const _ChatEvent_name = "Notify_joinNotify_leaveNotify_onlineNotify_offlineMessageAlert_error"

var _ChatEvent_index = [...]uint8{0, 11, 23, 36, 50, 57, 68}

func (i ChatEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChatEvent_index)-1 {
		return "ChatEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChatEvent_name[_ChatEvent_index[idx]:_ChatEvent_index[idx+1]]
}
