@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
actor client.A as client
actor client.B as bclient
box socket.IO
participant socket.server as server <<(C,#ADD1B2)>>
participant socket.room as room <<(C,#ADD1B2)>>
end box
collections mongoDb

client ->> server : on ev=message
server -> server : FetchSockets
server -> room : broadcast to socket
room -->> server
server ->> bclient : emit ev=message with ack
alt ack immediately < 1 second
    bclient -> server : ack
    & room -> mongoDb : cache message
else client already disconnect

@enduml