// Code generated by mockery v2.53.5. DO NOT EDIT.

package inetproto

import (
	context "context"
	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockHttpInterface is an autogenerated mock type for the HttpInterface type
type MockHttpInterface struct {
	mock.Mock
}

// BindResponse provides a mock function with given fields: res, payload
func (_m *MockHttpInterface) BindResponse(res *http.Response, payload interface{}) error {
	ret := _m.Called(res, payload)

	if len(ret) == 0 {
		panic("no return value specified for BindResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Response, interface{}) error); ok {
		r0 = rf(res, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRequest provides a mock function with given fields: ctx, header, method, url, body
func (_m *MockHttpInterface) CreateRequest(ctx context.Context, header []RequestHeader, method string, url string, body interface{}) (*http.Request, error) {
	ret := _m.Called(ctx, header, method, url, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []RequestHeader, string, string, interface{}) (*http.Request, error)); ok {
		return rf(ctx, header, method, url, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []RequestHeader, string, string, interface{}) *http.Request); ok {
		r0 = rf(ctx, header, method, url, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []RequestHeader, string, string, interface{}) error); ok {
		r1 = rf(ctx, header, method, url, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Do provides a mock function with given fields: req
func (_m *MockHttpInterface) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRequestWithContext provides a mock function with given fields: ctx, method, url, body
func (_m *MockHttpInterface) NewRequestWithContext(ctx context.Context, method string, url string, body io.Reader) (*http.Request, error) {
	ret := _m.Called(ctx, method, url, body)

	if len(ret) == 0 {
		panic("no return value specified for NewRequestWithContext")
	}

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) (*http.Request, error)); ok {
		return rf(ctx, method, url, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) *http.Request); ok {
		r0 = rf(ctx, method, url, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader) error); ok {
		r1 = rf(ctx, method, url, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadRequest provides a mock function with given fields: req
func (_m *MockHttpInterface) ReadRequest(req interface{}) io.Reader {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ReadRequest")
	}

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(interface{}) io.Reader); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	return r0
}

// NewMockHttpInterface creates a new instance of MockHttpInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHttpInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHttpInterface {
	mock := &MockHttpInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
