-- Summary Homepage Table
CREATE TABLE IF NOT EXISTS summary_homepage (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    terapis INT NOT NULL DEFAULT 0,
    kota INT NOT NULL DEFAULT 0,
    rating INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
