// Code generated by mockery v2.53.5. DO NOT EDIT.

package logger

import (
	sentry "github.com/getsentry/sentry-go"
	mock "github.com/stretchr/testify/mock"
)

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

// CaptureException provides a mock function with given fields: exception
func (_m *MockHub) CaptureException(exception error) *sentry.EventID {
	ret := _m.Called(exception)

	if len(ret) == 0 {
		panic("no return value specified for CaptureException")
	}

	var r0 *sentry.EventID
	if rf, ok := ret.Get(0).(func(error) *sentry.EventID); ok {
		r0 = rf(exception)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sentry.EventID)
		}
	}

	return r0
}

// CaptureMessage provides a mock function with given fields: message
func (_m *MockHub) CaptureMessage(message string) *sentry.EventID {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for CaptureMessage")
	}

	var r0 *sentry.EventID
	if rf, ok := ret.Get(0).(func(string) *sentry.EventID); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sentry.EventID)
		}
	}

	return r0
}

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
