// Code generated by mockery v2.53.5. DO NOT EDIT.

package logger

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockCatcher is an autogenerated mock type for the Catcher type
type MockCatcher struct {
	mock.Mock
}

// CaptureMessage provides a mock function with given fields: msg
func (_m *MockCatcher) CaptureMessage(msg string) {
	_m.Called(msg)
}

// Catch provides a mock function with given fields: err
func (_m *MockCatcher) Catch(err error) {
	_m.Called(err)
}

// SetHubFromContext provides a mock function with given fields: ctx
func (_m *MockCatcher) SetHubFromContext(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewMockCatcher creates a new instance of MockCatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatcher {
	mock := &MockCatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
