// Code generated by "stringer -type=ResponseMessage"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginPasswordMismatch-0]
	_ = x[LoginUnverified-1]
	_ = x[RegisterEmailUsed-2]
	_ = x[EmailNotFound-3]
	_ = x[VerifyOtpExpired-4]
	_ = x[UserAlreadyVerified-5]
	_ = x[AccessNotAllowed-6]
	_ = x[SessionExpired-7]
	_ = x[InternalError-8]
	_ = x[LogoutSuccess-9]
	_ = x[LoginSuccess-10]
	_ = x[RegisterSuccess-11]
	_ = x[VerifyOtpSuccess-12]
	_ = x[ResendOtpSuccess-13]
	_ = x[UserNotFound-14]
	_ = x[CreateUser-15]
	_ = x[UpdateUser-16]
	_ = x[DeleteUser-17]
	_ = x[GetDetailUser-18]
	_ = x[GetListUser-19]
	_ = x[CreateService-20]
	_ = x[UpdateService-21]
	_ = x[DeleteService-22]
	_ = x[GetDetailService-23]
	_ = x[GetListService-24]
	_ = x[GetCategories-25]
	_ = x[ServiceNotFound-26]
	_ = x[GetChatList-27]
	_ = x[RoomChatNotFound-28]
	_ = x[RoomNotValid-29]
	_ = x[BookingNotFound-30]
	_ = x[UpdateStatusBooking-31]
	_ = x[DropdownTherapistSuccess-32]
	_ = x[DropdownCitySuccess-33]
	_ = x[SettingIsNotSet-34]
}

const _ResponseMessage_name = "LoginPasswordMismatchLoginUnverifiedRegisterEmailUsedEmailNotFoundVerifyOtpExpiredUserAlreadyVerifiedAccessNotAllowedSessionExpiredInternalErrorLogoutSuccessLoginSuccessRegisterSuccessVerifyOtpSuccessResendOtpSuccessUserNotFoundCreateUserUpdateUserDeleteUserGetDetailUserGetListUserCreateServiceUpdateServiceDeleteServiceGetDetailServiceGetListServiceGetCategoriesServiceNotFoundGetChatListRoomChatNotFoundRoomNotValidBookingNotFoundUpdateStatusBookingDropdownTherapistSuccessDropdownCitySuccessSettingIsNotSet"

var _ResponseMessage_index = [...]uint16{0, 21, 36, 53, 66, 82, 101, 117, 131, 144, 157, 169, 184, 200, 216, 228, 238, 248, 258, 271, 282, 295, 308, 321, 337, 351, 364, 379, 390, 406, 418, 433, 452, 476, 495, 510}

func (i ResponseMessage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResponseMessage_index)-1 {
		return "ResponseMessage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseMessage_name[_ResponseMessage_index[idx]:_ResponseMessage_index[idx+1]]
}
