// Code generated by mockery v2.53.5. DO NOT EDIT.

package davinci

import mock "github.com/stretchr/testify/mock"

// MockUniquePredicate is an autogenerated mock type for the UniquePredicate type
type MockUniquePredicate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: result
func (_m *MockUniquePredicate) Execute(result string) (bool, error) {
	ret := _m.Called(result)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(result)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(result)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUniquePredicate creates a new instance of MockUniquePredicate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUniquePredicate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUniquePredicate {
	mock := &MockUniquePredicate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
