// Code generated by mockery v2.53.5. DO NOT EDIT.

package time

import (
	context "context"
	time2 "time"

	mock "github.com/stretchr/testify/mock"
)

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

// GetTimeZoneByName provides a mock function with given fields: name
func (_m *MockClock) GetTimeZoneByName(name string) *time2.Location {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeZoneByName")
	}

	var r0 *time2.Location
	if rf, ok := ret.Get(0).(func(string) *time2.Location); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time2.Location)
		}
	}

	return r0
}

// GetTimezoneFromContext provides a mock function with given fields: ctx
func (_m *MockClock) GetTimezoneFromContext(ctx context.Context) *time2.Location {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTimezoneFromContext")
	}

	var r0 *time2.Location
	if rf, ok := ret.Get(0).(func(context.Context) *time2.Location); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time2.Location)
		}
	}

	return r0
}

// Now provides a mock function with given fields: ctx
func (_m *MockClock) Now(ctx context.Context) time2.Time {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time2.Time
	if rf, ok := ret.Get(0).(func(context.Context) time2.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time2.Time)
	}

	return r0
}

// NowUnix provides a mock function with no fields
func (_m *MockClock) NowUnix() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NowUnix")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// ParseWithTzFromCtx provides a mock function with given fields: ctx, value, format
func (_m *MockClock) ParseWithTzFromCtx(ctx context.Context, value string, format string) time2.Time {
	ret := _m.Called(ctx, value, format)

	if len(ret) == 0 {
		panic("no return value specified for ParseWithTzFromCtx")
	}

	var r0 time2.Time
	if rf, ok := ret.Get(0).(func(context.Context, string, string) time2.Time); ok {
		r0 = rf(ctx, value, format)
	} else {
		r0 = ret.Get(0).(time2.Time)
	}

	return r0
}

// SetTimezoneToContext provides a mock function with given fields: ctx, val
func (_m *MockClock) SetTimezoneToContext(ctx context.Context, val string) context.Context {
	ret := _m.Called(ctx, val)

	if len(ret) == 0 {
		panic("no return value specified for SetTimezoneToContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(ctx, val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
